### ISSUE TITLE
Queryset Preload Methods Repeat Keys

### ISSUE THREAD

**Issue by DazedNConfused-** [jirfag/go-queryset#23]
When writing a Query that involves preloading a foreign-key object (for example: `DBModel.NewObjectQuerySet(DBConn).PrimaryKeyEq(pk).PreloadNestedObject()`), the _Nested Objects_ are fetched in a query that has a `WHERE` clause with all the foreign-key IDs.

The problem arises when said _Nested Objects_ are the same for multiple instances of `Object` (a many-to-one relationship); the underlying query repeats the key. For example:

| Object PK | Nested Object FK |
| --------- | ---------------- |
| 1         | 1                |
| 2         | 2                |
| 3         | 1                |
| 4         | 1                |
| 5         | 1                |

Results in the following query when using `PreloadNestedObject()`:

`SELECT * FROM NestedObject WHERE pk IN (1, 1, 1, 1, 2);`

This massively slows down the underlying queries when fetching fairly average resultsets (tens of seconds every 30000 simple records).

**Comment by jirfag** [comment]
@DazedNConfused- thank you for issue and nice formatting, but I can't control this behaviour in go-queryset. It's a [gorm issue](https://github.com/jinzhu/gorm/issues/1672). As I understood it was fixed in [this commit](https://github.com/jinzhu/gorm/commit/84b13be64cef6cadd27bf3cca4cd0e2dc3e28b0c), please try updating gorm

**Comment by DazedNConfused-** [comment]
Thank you for the heads-up! I have updated gorm but the behaviour persists. Perhaps it wasn't pushed to upstream yet.
